### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by SallyHaefling** [SallyHaefling/color-catcher-frontend#16]
Create a wireframe for project and try to stick to it. Please remember that wireframes are not to be copied exactly as-is. Take liberties and build a UI that makes sense, and is intuitive for your users.

**Comment by lboyer4** [comment]
<img width="731" alt="ColorCatcherFigma" src="https://user-images.githubusercontent.com/44039508/60560226-340dd180-9d0c-11e9-9e58-38a3e295c0ff.png">

**Comment by SallyHaefling** [comment]
Completed - please see comment
